# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# repos:
#   - repo: https://github.com/PyCQA/autoflake
#     rev: v2.0.1
#     hooks:
#       - id: autoflake

#   - repo: 'https://github.com/pre-commit/pre-commit-hooks'
#     rev: v4.4.0
#     hooks:
#       - id: check-yaml
#       - id: check-toml
#       # предупреждает о добавлении больших файлов в Git
#       - id: check-added-large-files
#       # предупреждает о сохранении файлов с UTF-8 BOM
#       - id: check-byte-order-marker
#       # предотвращает сохранение приватных ключей
#       - id: detect-private-key
#       # проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python
#       - id: check-ast

#   - repo: https://github.com/PyCQA/isort
#     rev: 5.12.0
#     hooks:
#       - id: isort
#         args: ["--profile", "black"]

#   - repo: https://github.com/psf/black
#     rev: 23.7.0
#     hooks:
#       - id: black
#         exclude: ^.*\b(migrations)\b.*$

#   - repo: https://github.com/pycqa/flake8
#     rev: 6.0.0
#     additional_dependencies: [cfg]
#     hooks:
#       - id: flake8


exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [filename, .env]
        exclude: .env.example

# install
# poetry add pre-commit --group dev
# pre-commit install

# run check
# pre-commit run --show-diff-on-failure --color=always --all-files
