# --------- Black -------------

[tool.black]
line-length = 119
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

# --------- Isort -------------

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
skip_gitignore = true
use_parentheses = true
ensure_newline_before_comments = true
# src_paths = ["src", "test"]

# --------- AutoFlake -------------

[tool.autoflake]
remove-all-unused-imports = true
expand-star-imports = true
remove-duplicate-keys = true
remove-unused-variables = true

# --------- Flake8 -------------

[tool.flake8]
max-line-length = 119
inline-quotes = "double"
max-methods = 14
exclude = ["research", "elk/main.py"]
ignore = """
    # I001: isort found an import in the wrong position
    I001,
    # I004: isort found an unexpected blank line in imports
    I004,
    # I005: isort found an unexpected missing import
    I005,
    # WPS214: Found too many methods
    WPS214,
    # WPS237 Found a too complex `f` string
    WPS237,
    # WPS305: Found `f` string
    WPS305,
    #  WPS306: Found class without a base class
    WPS306
    # WPS352: Found multiline loop
    WPS352,
    # WPS421: Found wrong function call: print
    WPS421,
    """
max-complexity = 10
docstring-convention = "numpy"

# --------- Mypy -------------

[tool.mypy]
show_error_codes = true
follow_imports = "silent"
ignore_missing_imports = false
strict_optional = true
check_untyped_defs = true
no_implicit_reexport = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true
