version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: test_database
      POSTGRES_PASSWORD: 123qwe  # pragma: allowlist secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
