# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:4.4.23-rc0-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  # pragma: allowlist secret
    volumes:
      - ./db/mongo:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  # pragma: allowlist secret
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  # pragma: allowlist secret
    depends_on:
      mongo:
        healthcheck: service_healthy
