version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: test_database
      POSTGRES_PASSWORD: 123qwe
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
